"use client"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [light, setLight] = useState(false)
  const [dark, setDark] = useState(false)
  
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* if the setDark is true, it will turn into the dark mode. */}
        {...dark && (className="bg-black")}
        
        {/* if the setLight is true, it will turn into the light mode. */}
        {...light && (className="bg-white")}
        <div className='flex flex-col'>
          <div>Blog App</div>
          <div>
            <button onClick={setLight(true)}>Light theme</button>
            <button onClick={setDark(true)}>Dark theme</button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
